spring:
  #页面配置
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    encoding: utf-8
    mode: LEGACYHTML5
    suffix: .html
    check-template-location: true
    servlet:
      content-type: text/html
  #静态资源
  mvc:
    static-path-pattern: /**
  #数据库配置
  datasource:
    #url: jdbc:mysql://39.106.28.199:3306/midb?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/midb?characterEncoding=utf8&useSSL=false
    password: root
    username: root
  #热部署
  devtools:
    restart:
      exclude: static/**,templates/**
  #AOP
  aop:
    proxy-target-class: true
  # Redis数据库
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #host: 39.106.28.199
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password: wangjiaxu
    # lettuce基于Netty的连接实例,可以在多个线程间并发访问，且线程安全，满足多线程环境下的并发访问
    #lettuce:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0

#MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-conf.xml
#tomcat
server:
  port: 8888
  servlet:
    context-path: /
#自定义属性
indexPath: ${random.value}

#日志
logging:
  level:
    com.wjx.mapper.*: debug
  config: classpath:logback.xml
  path: /log  #C:\log文件夹
